FROM ubuntu:trusty

RUN apt-get -y update && \
    apt-get -y install software-properties-common && \
    apt-add-repository -y ppa:ansible/ansible && \
    apt-get -y update && \
    apt-get -y install ansible
