FROM ubuntu:precise

RUN apt-get -y update && \
    apt-get -y install python-software-properties && \
    apt-get install build-essential libssl-dev libffi-dev python-dev && \
    pip install --upgrade pip && \
    pip install ansible
