FROM ubuntu:precise

RUN apt-get -y update && \
    apt-get -y install python-software-properties && \
    apt-add-repository -y ppa:ansible/ansible && \
    apt-get -y update && \
    apt-get -y install ansible
