FROM ubuntu:precise

RUN apt-get -y update && \
    apt-get -y install python-software-properties && \
    add-apt-repository -y ppa:rquillo/ansible && \
    apt-get -y update && \
    apt-get install -y ansible
